feature/user_update
Spica12/PythonWEB-PhotoShare pull request #32
Opened 2024-02-21 15:32 UTC by SergiyDovgopolyk

Таке діло, вже нема терпіння і сил: зробив апдейт current_user, але не можу зрозуміти чого не працює.. при апдейті 500-ту видає

2024-02-21 16:36 UTC, Spica12 requested changes

2024-02-21 16:36 UTC, Spica12 commented on src/repositories/users.py
> +from src.schemas.users import UserSchema, UserUpdate
Зміни схему UserUpdate на UserUpdateSchema

2024-02-21 16:36 UTC, Spica12 commented on src/repositories/users.py
> +from src.services import auth
Не роби імпорт сервіса в репозиторії. якщо треба то реалізуй логіку в сервісі....

2024-02-21 16:36 UTC, Spica12 commented on src/repositories/users.py
> +                    setattr(user, field, auth.auth_service.get_password_hash(value))
логіку сервіса реалізуй в сервісі...

2024-02-21 16:36 UTC, Spica12 commented on src/routers/users.py
> +        auth_service: AuthService = Depends(),
Навіщо? зверху вже імпортовано auth_service

2024-02-21 19:43 UTC, SergiyDovgopolyk commented on src/repositories/users.py
> +from src.schemas.users import UserSchema, UserUpdate
Так такої немає схеми... якщо просто перейменувати, то який з цього сенс?

2024-02-22 17:39 UTC, Spica12 commented on src/repositories/users.py
> +from src.schemas.users import UserSchema, UserUpdate
В тому що, щоб було легше зрозуміти про який клас йдеться мова, це модель або схема, тому в назві класу додали Schema.

2024-02-23 11:56 UTC, closed without merging