Psw reset
Spica12/PythonWEB-PhotoShare pull request #41
Opened 2024-02-22 21:29 UTC by Andriiok

pswd reset

2024-02-23 20:25 UTC, Spica12 requested changes

2024-02-23 20:25 UTC, Spica12 commented on src/services/auth.py
> +        user = await self.get_user_by_email(email, db)
Винести в router

2024-02-23 20:25 UTC, Spica12 commented on src/services/auth.py
> +        if user:
Перевірку чи існує юзер виконати в router, якщо ні, то повертати помилку 404.

2024-02-23 20:25 UTC, Spica12 commented on src/services/auth.py
> +            try:
навіщо тут через try?

2024-02-23 20:25 UTC, Spica12 commented on src/services/auth.py
> +    async def send_password_reset_notification(self, email, new_password):
це метод EmailService, то перенести її туди. Визивати з router

2024-02-25 12:22 UTC, Artificer-ua commented on src/repositories/users.py
> +            or_(UserModel.email == email, UserModel.username == username)
may be and_ ?

2024-02-26 05:30 UTC, closed without merging