feature/put_routes
Spica12/PythonWEB-PhotoShare pull request #43
Opened 2024-02-23 12:07 UTC by SergiyDovgopolyk

ban_user function - works correctly
update_current_user - it works, but I can't understand why the password is not overwritten in the database. Please check and help)

2024-02-23 13:59 UTC, Artificer-ua requested changes
Look at comments

2024-02-23 13:59 UTC, Artificer-ua commented on src/routers/users.py
> +async def ban_user(username: str, db: AsyncSession = Depends(get_db)):
Цей маршрут має бути доступний тільки для адміна. Не для всіх користувачів.
В тому числі якщо ми захочемо міняти ще якісь поля - це не просто бан юзер.

2024-02-23 13:59 UTC, Artificer-ua commented on src/services/auth.py
> +                status_code=status.HTTP_404_NOT_FOUND, detail=messages.USER_NOT_FOUND
Рейзити помилку HTTPException не в роутах не сильно правильно

2024-02-23 13:59 UTC, Artificer-ua commented on src/routers/users.py
> +        return {"result": f"{user.username}, your password has been updated!"}
Наче ж вирішили не міняти пароль через профіль, тільки скидувати через пошту?

2024-02-23 13:59 UTC, Artificer-ua commented on src/routers/users.py
> +            status_code=500, detail=f"An unexpected error occurred. Report this message to support: {e}")
500+ помилки це помилки сервера. Мы їх не генеруємо і не повертаємо.

2024-02-23 13:59 UTC, Artificer-ua commented on src/routers/users.py
> +            status_code=400, detail=f"{e}")
Правильніше повертати: status.HTTP_400_BAD_REQUEST
Але і 400 тут спірна.

2024-02-23 13:59 UTC, Artificer-ua commented on src/routers/users.py
> +        auth_service: AuthService = Depends(),
Чому прибраний Depends? 
Навіть якщо не потрібно визначати current_user, то перегляд профілю закритий для не зареєстрованих.

2024-02-24 09:02 UTC, SergiyDovgopolyk commented on src/routers/users.py
> +        return {"result": f"{user.username}, your password has been updated!"}
Цей функціонал Андрій пише, я так зрозумів..  Тоді мені переписати на змінення полів юзернейм та емейл, чи як?

2024-02-24 09:03 UTC, SergiyDovgopolyk commented on src/services/auth.py
> +                status_code=status.HTTP_404_NOT_FOUND, detail=messages.USER_NOT_FOUND
Якщо не принципіально, давай залишим так, бо працює)))

2024-02-24 09:08 UTC, SergiyDovgopolyk commented on src/routers/users.py
> +            status_code=500, detail=f"An unexpected error occurred. Report this message to support: {e}")
Тут безспіно згоден, виправлю

2024-02-24 09:13 UTC, SergiyDovgopolyk commented on src/routers/users.py
> +            status_code=400, detail=f"{e}")
Виправив на status.HTTP_400_BAD_REQUEST

2024-02-24 09:35 UTC, SergiyDovgopolyk commented on src/routers/users.py
> +        auth_service: AuthService = Depends(),
Згоден, поправив. Не зареєстрований користувач не може переглядати профіль іншого користувача

2024-02-24 09:37 UTC, SergiyDovgopolyk commented on src/routers/users.py
> +async def ban_user(username: str, db: AsyncSession = Depends(get_db)):
Згоден, виправив

2024-02-25 09:43 UTC, Spica12 requested changes

2024-02-25 09:43 UTC, Spica12 commented on src/routers/users.py
> +    if not current_user:
Я думаю, що ця перевірка не потрібна, тому що в вже є `current_user: UserModel = Depends(get_current_user)` . Пропоную прибрати, але якщо треба, то обгрунтувати

2024-02-25 09:43 UTC, Spica12 commented on src/routers/users.py
> +            detail="User not found."
Використати повідомлення з файла src/conf/messages.py.

2024-02-25 09:43 UTC, Spica12 commented on src/routers/users.py
> +def is_admin(user: UserModel = Depends(auth_service.get_current_user)):
МОже не потрібно? можна реалзіувати перевірку на адміна за допомогою `dependencies=[Depends(RoleChecker([Roles.admin]))]`

2024-02-25 09:43 UTC, Spica12 commented on src/routers/users.py
>  @router_users.put(
Додати сюди перевірку на адміна
dependencies=[Depends(RoleChecker([Roles.admin]))]

2024-02-25 09:43 UTC, Spica12 commented on src/routers/users.py
> +    if not current_user:
Навіщо? Якщо current_user немає, то тебе навіть до сюди не пропустить. Зайва перевірка

2024-02-25 09:43 UTC, Spica12 commented on src/routers/users.py
> +    try:
Це реалізовується на рівні repositoriesа, а не routers

2024-02-25 09:43 UTC, Spica12 commented on src/routers/users.py
> +async def redirect_to_my_profile(username: str, current_user: UserModel = Depends(auth_service.get_current_user),
В чому різниця між маршрутом get_user?

2024-02-25 09:43 UTC, Spica12 commented on src/services/auth.py
> +    async def update_user(self, email: str, user_update: UserUpdateEmail, db: AsyncSession):
Реалізовано не через repositories

2024-02-26 23:26 UTC, closed without merging